// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: m5-qrcode-pos

#include "ui/ui.h"

lv_obj_t * ui_amount_state = NULL;
lv_obj_t * ui_header_1 = NULL;
lv_obj_t * ui_footer_1 = NULL;
lv_obj_t * ui_payment_btn_1 = NULL;
lv_obj_t * ui_back_btn_1 = NULL;
lv_obj_t * ui_amount_1 = NULL;
lv_obj_t * ui_label_1_0 = NULL;
lv_obj_t * ui_label_1_1 = NULL;
lv_obj_t * ui_amount_price_spn_1 = NULL;
lv_obj_t * ui_amount_plus_btn_1 = NULL;
lv_obj_t * ui_label_1_2 = NULL;
lv_obj_t * ui_amount_minus_btn_1 = NULL;
lv_obj_t * ui_label_1_3 = NULL;
lv_obj_t * ui_goods_list_1 = NULL;
lv_obj_t * ui_goods_list_title_lbl_1 = NULL;
lv_obj_t * ui_goods_list_number_lbl_1 = NULL;
lv_obj_t * ui_goods_list_price_lbl_1 = NULL;
// event funtions
void ui_event_payment_btn_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnAmountPaymentButtonClicked(e);
        _ui_screen_change(&ui_payment_state, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_payment_state_screen_init);
    }
}

void ui_event_back_btn_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnAmountBackButtonClicked(e);
        _ui_screen_change(&ui_goods_state, LV_SCR_LOAD_ANIM_OUT_RIGHT, 500, 0, &ui_goods_state_screen_init);
    }
}

void ui_event_amount_price_spn_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnAmountSpinboxValueChanged(e);
    }
}

void ui_event_amount_plus_btn_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_amount_price_spn_1, 1);
    }
}

void ui_event_amount_minus_btn_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_amount_price_spn_1, -1);
    }
}

// build funtions

void ui_amount_state_screen_init(void)
{
    ui_amount_state = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_amount_state, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_header_1 = ui_header_create(ui_amount_state);
    lv_obj_set_x(ui_header_1, 0);
    lv_obj_set_y(ui_header_1, 0);

    ui_footer_1 = lv_obj_create(ui_amount_state);
    lv_obj_set_width(ui_footer_1, 320);
    lv_obj_set_height(ui_footer_1, 48);
    lv_obj_set_x(ui_footer_1, 0);
    lv_obj_set_y(ui_footer_1, 192);
    lv_obj_remove_flag(ui_footer_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_footer_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_footer_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue_darken_1);
    ui_object_set_themeable_style_property(ui_footer_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue_darken_1);
    lv_obj_set_style_border_width(ui_footer_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_footer_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_footer_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_footer_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_footer_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_payment_btn_1 = lv_imagebutton_create(ui_footer_1);
    lv_imagebutton_set_src(ui_payment_btn_1, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_shopping_cart_48dp_e3e3e3_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_payment_btn_1, 48);
    lv_obj_set_height(ui_payment_btn_1, 48);
    lv_obj_set_x(ui_payment_btn_1, 216);
    lv_obj_set_y(ui_payment_btn_1, 0);
    lv_obj_set_align(ui_payment_btn_1, LV_ALIGN_LEFT_MID);
    ui_object_set_themeable_style_property(ui_payment_btn_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_payment_btn_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_border_width(ui_payment_btn_1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_back_btn_1 = lv_imagebutton_create(ui_footer_1);
    lv_imagebutton_set_src(ui_back_btn_1, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_arrow_back_48dp_e3e3e3_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_back_btn_1, 48);
    lv_obj_set_height(ui_back_btn_1, 48);
    lv_obj_set_align(ui_back_btn_1, LV_ALIGN_LEFT_MID);
    ui_object_set_themeable_style_property(ui_back_btn_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_back_btn_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_border_width(ui_back_btn_1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_amount_1 = lv_obj_create(ui_amount_state);
    lv_obj_set_width(ui_amount_1, 320);
    lv_obj_set_height(ui_amount_1, 168);
    lv_obj_set_x(ui_amount_1, 0);
    lv_obj_set_y(ui_amount_1, 24);
    lv_obj_remove_flag(ui_amount_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_amount_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_amount_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(ui_amount_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(ui_amount_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_amount_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_amount_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_amount_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_amount_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_1_0 = lv_label_create(ui_amount_1);
    lv_obj_set_width(ui_label_1_0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_1_0, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_label_1_0, 6);
    lv_obj_set_y(ui_label_1_0, 8);
    lv_label_set_text(ui_label_1_0, "金額入力");
    ui_object_set_themeable_style_property(ui_label_1_0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_label_1_0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_label_1_0, &ui_font_noto_sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_1_1 = lv_label_create(ui_amount_1);
    lv_obj_set_width(ui_label_1_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_1_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_1_1, 290);
    lv_obj_set_y(ui_label_1_1, 8);
    lv_label_set_text(ui_label_1_1, "円");
    ui_object_set_themeable_style_property(ui_label_1_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_label_1_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_label_1_1, &ui_font_noto_sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_amount_price_spn_1 = lv_spinbox_create(ui_amount_1);
    lv_obj_set_width(ui_amount_price_spn_1, 96);
    lv_obj_set_height(ui_amount_price_spn_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_amount_price_spn_1, 148);
    lv_obj_set_y(ui_amount_price_spn_1, 0);
    lv_spinbox_set_digit_format(ui_amount_price_spn_1, 4, 0);
    lv_spinbox_set_range(ui_amount_price_spn_1, -9900, 9900);
    lv_spinbox_set_cursor_pos(ui_amount_price_spn_1, 3 - 1);
    lv_spinbox_set_step(ui_amount_price_spn_1, 100);
    ui_object_set_themeable_style_property(ui_amount_price_spn_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_amount_price_spn_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_align(ui_amount_price_spn_1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_amount_price_spn_1, &ui_font_noto_sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_amount_price_spn_1, LV_PART_CURSOR | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_amount_price_spn_1, LV_PART_CURSOR | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);

    ui_amount_plus_btn_1 = lv_button_create(ui_amount_1);
    lv_obj_set_width(ui_amount_plus_btn_1, 36);
    lv_obj_set_height(ui_amount_plus_btn_1, 36);
    lv_obj_set_x(ui_amount_plus_btn_1, 248);
    lv_obj_set_y(ui_amount_plus_btn_1, 6);
    lv_obj_add_flag(ui_amount_plus_btn_1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_amount_plus_btn_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_label_1_2 = lv_label_create(ui_amount_plus_btn_1);
    lv_obj_set_width(ui_label_1_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_1_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_1_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_1_2, "+");
    ui_object_set_themeable_style_property(ui_label_1_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_label_1_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_label_1_2, &ui_font_noto_sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_amount_minus_btn_1 = lv_button_create(ui_amount_1);
    lv_obj_set_width(ui_amount_minus_btn_1, 36);
    lv_obj_set_height(ui_amount_minus_btn_1, 36);
    lv_obj_set_x(ui_amount_minus_btn_1, 108);
    lv_obj_set_y(ui_amount_minus_btn_1, 6);
    lv_obj_add_flag(ui_amount_minus_btn_1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_amount_minus_btn_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_label_1_3 = lv_label_create(ui_amount_minus_btn_1);
    lv_obj_set_width(ui_label_1_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_1_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_1_3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_1_3, "-");
    ui_object_set_themeable_style_property(ui_label_1_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_label_1_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_label_1_3, &ui_font_noto_sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goods_list_1 = lv_obj_create(ui_amount_1);
    lv_obj_set_width(ui_goods_list_1, 272);
    lv_obj_set_height(ui_goods_list_1, 120);
    lv_obj_set_x(ui_goods_list_1, 24);
    lv_obj_set_y(ui_goods_list_1, 48);
    lv_obj_set_style_radius(ui_goods_list_1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_goods_list_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(ui_goods_list_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    ui_object_set_themeable_style_property(ui_goods_list_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_goods_list_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_pad_left(ui_goods_list_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_goods_list_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_goods_list_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_goods_list_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goods_list_title_lbl_1 = lv_label_create(ui_goods_list_1);
    lv_obj_set_width(ui_goods_list_title_lbl_1, 160);
    lv_obj_set_height(ui_goods_list_title_lbl_1, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_goods_list_title_lbl_1, "商品タイトル");
    ui_object_set_themeable_style_property(ui_goods_list_title_lbl_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_goods_list_title_lbl_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_goods_list_title_lbl_1, &ui_font_noto_sans_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goods_list_number_lbl_1 = lv_label_create(ui_goods_list_1);
    lv_obj_set_width(ui_goods_list_number_lbl_1, 40);
    lv_obj_set_height(ui_goods_list_number_lbl_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_goods_list_number_lbl_1, 160);
    lv_obj_set_y(ui_goods_list_number_lbl_1, 0);
    lv_label_set_text(ui_goods_list_number_lbl_1, "x000");
    ui_object_set_themeable_style_property(ui_goods_list_number_lbl_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_goods_list_number_lbl_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_goods_list_number_lbl_1, &ui_font_noto_sans_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goods_list_price_lbl_1 = lv_label_create(ui_goods_list_1);
    lv_obj_set_width(ui_goods_list_price_lbl_1, 72);
    lv_obj_set_height(ui_goods_list_price_lbl_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_goods_list_price_lbl_1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_goods_list_price_lbl_1, "000000円");
    ui_object_set_themeable_style_property(ui_goods_list_price_lbl_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_goods_list_price_lbl_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_align(ui_goods_list_price_lbl_1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_goods_list_price_lbl_1, &ui_font_noto_sans_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_payment_btn_1, ui_event_payment_btn_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_back_btn_1, ui_event_back_btn_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_amount_price_spn_1, ui_event_amount_price_spn_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_amount_plus_btn_1, ui_event_amount_plus_btn_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_amount_minus_btn_1, ui_event_amount_minus_btn_1, LV_EVENT_ALL, NULL);

}

void ui_amount_state_screen_destroy(void)
{
    if(ui_amount_state) lv_obj_del(ui_amount_state);

    // NULL screen variables
    ui_amount_state = NULL;
    ui_header_1 = NULL;
    ui_footer_1 = NULL;
    ui_payment_btn_1 = NULL;
    ui_back_btn_1 = NULL;
    ui_amount_1 = NULL;
    ui_label_1_0 = NULL;
    ui_label_1_1 = NULL;
    ui_amount_price_spn_1 = NULL;
    ui_amount_plus_btn_1 = NULL;
    ui_label_1_2 = NULL;
    ui_amount_minus_btn_1 = NULL;
    ui_label_1_3 = NULL;
    ui_goods_list_1 = NULL;
    ui_goods_list_title_lbl_1 = NULL;
    ui_goods_list_number_lbl_1 = NULL;
    ui_goods_list_price_lbl_1 = NULL;

}
