// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: m5-qrcode-pos

#include "ui/ui.h"

// COMPONENT header

lv_obj_t * ui_header_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_header;
    cui_header = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_header, 320);
    lv_obj_set_height(cui_header, 24);
    lv_obj_remove_flag(cui_header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_header, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue_darken_1);
    ui_object_set_themeable_style_property(cui_header, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue_darken_1);
    lv_obj_set_style_border_width(cui_header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_battery_img;
    cui_battery_img = lv_image_create(cui_header);
    lv_image_set_src(cui_battery_img, &ui_img_battery_android_full_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(cui_battery_img, 24);
    lv_obj_set_height(cui_battery_img, 24);
    lv_obj_set_align(cui_battery_img, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(cui_battery_img, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_battery_img, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_time_lbl;
    cui_time_lbl = lv_label_create(cui_header);
    lv_obj_set_width(cui_time_lbl, 108);
    lv_obj_set_height(cui_time_lbl, 20);
    lv_obj_set_x(cui_time_lbl, 24);
    lv_obj_set_y(cui_time_lbl, 0);
    lv_obj_set_align(cui_time_lbl, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_time_lbl, "00:00:00");
    lv_obj_remove_flag(cui_time_lbl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(cui_time_lbl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(cui_time_lbl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(cui_time_lbl, &ui_font_dseg7_20pt, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_HEADER_NUM);
    children[UI_COMP_HEADER_HEADER] = cui_header;
    children[UI_COMP_HEADER_BATTERY_IMG] = cui_battery_img;
    children[UI_COMP_HEADER_TIME_LBL] = cui_time_lbl;
    lv_obj_add_event_cb(cui_header, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_header, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_header_create_hook(cui_header);
    return cui_header;
}

