// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: m5-qrcode-pos

#include "ui/ui.h"

#include "states/state_selector.h"
#include "states/goods_state.h"
#include "states/payment_state.h"

void OnBarcodeButtonClicked(lv_event_t * e)
{
	// Your code here
	GoodsState::OnQRCodeButtonClicked();
}

void OnAddButtonClicked(lv_event_t * e)
{
	// Your code here
	GoodsState::OnPlusButtonClicked();
}

void OnRemoveButtonClicked(lv_event_t * e)
{
	// Your code here
	GoodsState::OnMinusButtonClicked();
}

void OnTotalPriceLabelLongPressed(lv_event_t * e)
{
	// Your code here
	GoodsState::OnResetButtonClicked();
}

void OnGoodsPrevButtonClicked(lv_event_t * e)
{
	// Your code here
	GoodsState::OnGoodsPrevButtonClicked();
}

void OnGoodsNextButtonClicked(lv_event_t * e)
{
	// Your code here
	GoodsState::OnGoodsNextButtonClicked();
}

void OnGoodsAmountButtonClicked(lv_event_t * e)
{
	// Your code here
}

void OnGoodsPaymentButtonClicked(lv_event_t * e)
{
	// Your code here
	StateSelector::ToPaymentState();
}

void OnAmountBackButtonClicked(lv_event_t * e)
{
	// Your code here
	StateSelector::ToGoodsState();
}

void OnAmountPaymentButtonClicked(lv_event_t * e)
{
	// Your code here
	StateSelector::ToGoodsState();
}

void OnGoodsSettingsButtonClicked(lv_event_t * e)
{
	// Your code here
}

void OnAmountSpinboxValueChanged(lv_event_t * e)
{
	// Your code here
}

void OnPaymentBackButtonClicked(lv_event_t * e)
{
	// Your code here
	StateSelector::ToGoodsState();
}

void OnPaymentFreeButtonClicked(lv_event_t * e)
{
	// Your code here
	PaymentState::OnFreeButtonClicked();
	StateSelector::ToGoodsState();
}

void OnPaymentOkayButtonClicked(lv_event_t * e)
{
	// Your code here
	PaymentState::OnOkayButtonClicked();
	StateSelector::ToGoodsState();
}

void OnSettingsBackButtonClicked(lv_event_t * e)
{
	// Your code here
	StateSelector::ToGoodsState();
}

void OnSettingsPlusButtonClicked(lv_event_t * e)
{
	// Your code here
}

void OnSettingsMinusButtonClicked(lv_event_t * e)
{
	// Your code here
}

void OnSettingsOkayButtonClicked(lv_event_t * e)
{
	// Your code here
	StateSelector::ToGoodsState();
}

void OnYYYYLabelClicked(lv_event_t * e)
{
	// Your code here
}

void OnMM0LabelClicked(lv_event_t * e)
{
	// Your code here
}

void OnDDLabelClicked(lv_event_t * e)
{
	// Your code here
}

void OnHHLabelClicked(lv_event_t * e)
{
	// Your code here
}

void OnMM1LabelClicked(lv_event_t * e)
{
	// Your code here
}
