// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: m5-qrcode-pos

#include "ui/ui.h"

#include "states/state_selector.h"
#include "states/goods_state.h"
#include "states/amount_state.h"
#include "states/payment_state.h"
#include "states/settings_state.h"

void OnGoodsImageClicked(lv_event_t * e)
{
	// Your code here
	GoodsState::OnQRCodeButtonClicked();
}

void OnGoodsAddButtonClicked(lv_event_t * e)
{
	// Your code here
	GoodsState::OnPlusButtonClicked();
}

void OnGoodsRemoveButtonClicked(lv_event_t * e)
{
	// Your code here
	GoodsState::OnMinusButtonClicked();
}

void OnGoodsSalesButtonClicked(lv_event_t * e)
{
	// Your code here
}

void OnTotalPriceLabelLongPressed(lv_event_t * e)
{
	// Your code here
	GoodsState::OnResetButtonClicked();
}

void OnGoodsPrevButtonClicked(lv_event_t * e)
{
	// Your code here
	GoodsState::OnGoodsPrevButtonClicked();
}

void OnGoodsNextButtonClicked(lv_event_t * e)
{
	// Your code here
	GoodsState::OnGoodsNextButtonClicked();
}

void OnGoodsAmountButtonClicked(lv_event_t * e)
{
	// Your code here
	StateSelector::ToAmountState();
}

void OnGoodsPaymentButtonClicked(lv_event_t * e)
{
	// Your code here
	AmountState::OnPaymentButtonClicked();
	StateSelector::ToPaymentState();
}

void OnAmountBackButtonClicked(lv_event_t * e)
{
	// Your code here
	StateSelector::ToGoodsState();
}

void OnAmountPaymentButtonClicked(lv_event_t * e)
{
	// Your code here
	StateSelector::ToPaymentState();
}

void OnGoodsSettingsButtonClicked(lv_event_t * e)
{
	// Your code here
	StateSelector::ToSettingsState();
}

void OnAmountSpinboxValueChanged(lv_event_t * e)
{
	// Your code here
	AmountState::OnSpinBoxValueChanged();
}

void OnPaymentBackButtonClicked(lv_event_t * e)
{
	// Your code here
	StateSelector::ToGoodsState();
}

void OnPaymentFreeButtonClicked(lv_event_t * e)
{
	// Your code here
	PaymentState::OnFreeButtonClicked();
	StateSelector::ToGoodsState();
}

void OnPaymentOkayButtonClicked(lv_event_t * e)
{
	// Your code here
	PaymentState::OnOkayButtonClicked();
	StateSelector::ToGoodsState();
}

void OnSettingsBrightnessValueChanged(lv_event_t * e)
{
	// Your code here
}

void OnSettingsBackButtonClicked(lv_event_t * e)
{
	// Your code here
	StateSelector::ToGoodsState();
}

void OnSettingsLeftButtonClicked(lv_event_t * e)
{
	// Your code here
	SettingsState::OnLeftButtonClicked();
}

void OnSettingsRightButtonClicked(lv_event_t * e)
{
	// Your code here
	SettingsState::OnRightButtonClicked();
}

void OnSettingsPlusButtonClicked(lv_event_t * e)
{
	// Your code here
	SettingsState::OnPlusButtonClicked();
}

void OnSettingsMinusButtonClicked(lv_event_t * e)
{
	// Your code here
	SettingsState::OnMinusButtonClicked();
}

void OnSettingsOkayButtonClicked(lv_event_t * e)
{
	// Your code here
	SettingsState::OnOkayButtonClicked();
	StateSelector::ToGoodsState();
}

void OnYYYYLabelClicked(lv_event_t * e)
{
	// Your code here
	SettingsState::OnYYYYLabelClicked();
}

void OnMM0LabelClicked(lv_event_t * e)
{
	// Your code here
	SettingsState::OnMM0LabelClicked();
}

void OnDDLabelClicked(lv_event_t * e)
{
	// Your code here
	SettingsState::OnDDLabelClicked();
}

void OnHHLabelClicked(lv_event_t * e)
{
	// Your code here
	SettingsState::OnHHLabelClicked();
}

void OnMM1LabelClicked(lv_event_t * e)
{
	// Your code here
	SettingsState::OnMM1LabelClicked();
}

void OnSalesBackButtonClicked(lv_event_t * e)
{
	// Your code here
	StateSelector::ToGoodsState();
}