// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: m5-qrcode-pos

#include "ui/ui.h"

#include "states/goods_state.h"

void OnBarcodeButtonClicked(lv_event_t * e)
{
	// Your code here
	GoodsState::OnQRCodeButtonClicked();
}

void OnAddButtonClicked(lv_event_t * e)
{
	// Your code here
	GoodsState::OnPlusButtonClicked();
}

void OnRemoveButtonClicked(lv_event_t * e)
{
	// Your code here
	GoodsState::OnMinusButtonClicked();
}

void OnTotalPriceLabelLongPressed(lv_event_t * e)
{
	// Your code here
	GoodsState::OnResetButtonClicked();
}

void OnGoodsPrevButtonClicked(lv_event_t * e)
{
	// Your code here
	GoodsState::OnGoodsPrevButtonClicked();
}

void OnGoodsNextButtonClicked(lv_event_t * e)
{
	// Your code here
	GoodsState::OnGoodsNextButtonClicked();
}

void OnPaymentButtonClicked(lv_event_t * e)
{
	// Your code here
}

void OnSpinboxValueChanged(lv_event_t * e)
{
	// Your code here
}

void OnFreeButtonClicked(lv_event_t * e)
{
	// Your code here
}

void OnPaymentOkayButtonClicked(lv_event_t * e)
{
	// Your code here
}

void OnSettingsPlusButtonClicked(lv_event_t * e)
{
	// Your code here
}

void OnSettingsMinusButtonClicked(lv_event_t * e)
{
	// Your code here
}

void OnSettingsOkayButtonClicked(lv_event_t * e)
{
	// Your code here
}

void OnYYYYLabelClicked(lv_event_t * e)
{
	// Your code here
}

void OnMM0LabelClicked(lv_event_t * e)
{
	// Your code here
}

void OnDDLabelClicked(lv_event_t * e)
{
	// Your code here
}

void OnHHLabelClicked(lv_event_t * e)
{
	// Your code here
}

void OnMM1LabelClicked(lv_event_t * e)
{
	// Your code here
}
