// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: m5-qrcode-pos

#include "ui/ui.h"

lv_obj_t * ui_settings_state = NULL;
lv_obj_t * ui_header3 = NULL;
lv_obj_t * ui_footer_3 = NULL;
lv_obj_t * ui_back_btn_3 = NULL;
lv_obj_t * ui_plus_btn_3 = NULL;
lv_obj_t * ui_minus_btn_3 = NULL;
lv_obj_t * ui_cursor_left_btn_3 = NULL;
lv_obj_t * ui_cursor_right_btn_3 = NULL;
lv_obj_t * ui_okay_btn_3 = NULL;
lv_obj_t * ui_label_3_0 = NULL;
lv_obj_t * ui_time_yyyy_lbl_3 = NULL;
lv_obj_t * ui_label_3_1 = NULL;
lv_obj_t * ui_time_mm_lbl_3_0 = NULL;
lv_obj_t * ui_label_3_2 = NULL;
lv_obj_t * ui_time_dd_lbl_3 = NULL;
lv_obj_t * ui_tim_hh_lbl_3 = NULL;
lv_obj_t * ui_label_3_3 = NULL;
lv_obj_t * ui_time_mm_lbl_3_1 = NULL;
lv_obj_t * ui_label_3_4 = NULL;
lv_obj_t * ui_blightness_sld_3 = NULL;
// event funtions

// build funtions

void ui_settings_state_screen_init(void)
{
    ui_settings_state = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_settings_state, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_header3 = ui_header_create(ui_settings_state);
    lv_obj_set_x(ui_header3, 0);
    lv_obj_set_y(ui_header3, 0);

    ui_footer_3 = lv_obj_create(ui_settings_state);
    lv_obj_set_width(ui_footer_3, 320);
    lv_obj_set_height(ui_footer_3, 48);
    lv_obj_set_x(ui_footer_3, 0);
    lv_obj_set_y(ui_footer_3, 192);
    lv_obj_remove_flag(ui_footer_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_footer_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_footer_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue_darken_1);
    ui_object_set_themeable_style_property(ui_footer_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue_darken_1);
    lv_obj_set_style_border_width(ui_footer_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_footer_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_footer_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_footer_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_footer_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_back_btn_3 = lv_imagebutton_create(ui_footer_3);
    lv_imagebutton_set_src(ui_back_btn_3, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_arrow_back_48dp_e3e3e3_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_back_btn_3, 48);
    lv_obj_set_height(ui_back_btn_3, 48);
    lv_obj_set_align(ui_back_btn_3, LV_ALIGN_LEFT_MID);
    ui_object_set_themeable_style_property(ui_back_btn_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_back_btn_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_border_width(ui_back_btn_3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_plus_btn_3 = lv_imagebutton_create(ui_footer_3);
    lv_imagebutton_set_src(ui_plus_btn_3, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_add_48dp_e3e3e3_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_plus_btn_3, 48);
    lv_obj_set_height(ui_plus_btn_3, 48);
    lv_obj_set_x(ui_plus_btn_3, 162);
    lv_obj_set_y(ui_plus_btn_3, 0);
    lv_obj_set_align(ui_plus_btn_3, LV_ALIGN_LEFT_MID);
    ui_object_set_themeable_style_property(ui_plus_btn_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_plus_btn_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_border_width(ui_plus_btn_3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minus_btn_3 = lv_imagebutton_create(ui_footer_3);
    lv_imagebutton_set_src(ui_minus_btn_3, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_remove_48dp_e3e3e3_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_minus_btn_3, 48);
    lv_obj_set_height(ui_minus_btn_3, 48);
    lv_obj_set_x(ui_minus_btn_3, 216);
    lv_obj_set_y(ui_minus_btn_3, 0);
    lv_obj_set_align(ui_minus_btn_3, LV_ALIGN_LEFT_MID);
    ui_object_set_themeable_style_property(ui_minus_btn_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_minus_btn_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_border_width(ui_minus_btn_3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cursor_left_btn_3 = lv_imagebutton_create(ui_footer_3);
    lv_imagebutton_set_src(ui_cursor_left_btn_3, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_arrow_back_ios_new_48dp_e3e3e3_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_cursor_left_btn_3, 48);
    lv_obj_set_height(ui_cursor_left_btn_3, 48);
    lv_obj_set_x(ui_cursor_left_btn_3, 54);
    lv_obj_set_y(ui_cursor_left_btn_3, 0);
    lv_obj_set_align(ui_cursor_left_btn_3, LV_ALIGN_LEFT_MID);
    ui_object_set_themeable_style_property(ui_cursor_left_btn_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_cursor_left_btn_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_border_width(ui_cursor_left_btn_3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cursor_right_btn_3 = lv_imagebutton_create(ui_footer_3);
    lv_imagebutton_set_src(ui_cursor_right_btn_3, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_arrow_forward_ios_48dp_e3e3e3_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_cursor_right_btn_3, 48);
    lv_obj_set_height(ui_cursor_right_btn_3, 48);
    lv_obj_set_x(ui_cursor_right_btn_3, 108);
    lv_obj_set_y(ui_cursor_right_btn_3, 0);
    lv_obj_set_align(ui_cursor_right_btn_3, LV_ALIGN_LEFT_MID);
    ui_object_set_themeable_style_property(ui_cursor_right_btn_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_cursor_right_btn_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_border_width(ui_cursor_right_btn_3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_okay_btn_3 = lv_imagebutton_create(ui_footer_3);
    lv_imagebutton_set_src(ui_okay_btn_3, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_check_48dp_e3e3e3_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_okay_btn_3, 48);
    lv_obj_set_height(ui_okay_btn_3, 48);
    lv_obj_set_x(ui_okay_btn_3, 272);
    lv_obj_set_y(ui_okay_btn_3, 0);
    lv_obj_set_align(ui_okay_btn_3, LV_ALIGN_LEFT_MID);
    ui_object_set_themeable_style_property(ui_okay_btn_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_okay_btn_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_border_width(ui_okay_btn_3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_3_0 = lv_label_create(ui_settings_state);
    lv_obj_set_width(ui_label_3_0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_3_0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_3_0, 12);
    lv_obj_set_y(ui_label_3_0, 48);
    lv_label_set_text(ui_label_3_0, "日時");
    ui_object_set_themeable_style_property(ui_label_3_0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_label_3_0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_label_3_0, &ui_font_noto_sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time_yyyy_lbl_3 = lv_label_create(ui_settings_state);
    lv_obj_set_width(ui_time_yyyy_lbl_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_yyyy_lbl_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time_yyyy_lbl_3, 72);
    lv_obj_set_y(ui_time_yyyy_lbl_3, 52);
    lv_label_set_text(ui_time_yyyy_lbl_3, "0000");
    ui_object_set_themeable_style_property(ui_time_yyyy_lbl_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_yellow_light_1);
    ui_object_set_themeable_style_property(ui_time_yyyy_lbl_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_yellow_light_1);
    lv_obj_set_style_text_font(ui_time_yyyy_lbl_3, &ui_font_dseg7_20pt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_3_1 = lv_label_create(ui_settings_state);
    lv_obj_set_width(ui_label_3_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_3_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_3_1, 138);
    lv_obj_set_y(ui_label_3_1, 48);
    lv_label_set_text(ui_label_3_1, "/");
    ui_object_set_themeable_style_property(ui_label_3_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_label_3_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_label_3_1, &ui_font_noto_sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time_mm_lbl_3_0 = lv_label_create(ui_settings_state);
    lv_obj_set_width(ui_time_mm_lbl_3_0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_mm_lbl_3_0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time_mm_lbl_3_0, 148);
    lv_obj_set_y(ui_time_mm_lbl_3_0, 52);
    lv_label_set_text(ui_time_mm_lbl_3_0, "00");
    ui_object_set_themeable_style_property(ui_time_mm_lbl_3_0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_time_mm_lbl_3_0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_time_mm_lbl_3_0, &ui_font_dseg7_20pt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_3_2 = lv_label_create(ui_settings_state);
    lv_obj_set_width(ui_label_3_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_3_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_3_2, 182);
    lv_obj_set_y(ui_label_3_2, 48);
    lv_label_set_text(ui_label_3_2, "/");
    ui_object_set_themeable_style_property(ui_label_3_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_label_3_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_label_3_2, &ui_font_noto_sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time_dd_lbl_3 = lv_label_create(ui_settings_state);
    lv_obj_set_width(ui_time_dd_lbl_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_dd_lbl_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time_dd_lbl_3, 192);
    lv_obj_set_y(ui_time_dd_lbl_3, 52);
    lv_label_set_text(ui_time_dd_lbl_3, "00");
    ui_object_set_themeable_style_property(ui_time_dd_lbl_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_time_dd_lbl_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_time_dd_lbl_3, &ui_font_dseg7_20pt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tim_hh_lbl_3 = lv_label_create(ui_settings_state);
    lv_obj_set_width(ui_tim_hh_lbl_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tim_hh_lbl_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tim_hh_lbl_3, 240);
    lv_obj_set_y(ui_tim_hh_lbl_3, 52);
    lv_label_set_text(ui_tim_hh_lbl_3, "00");
    ui_object_set_themeable_style_property(ui_tim_hh_lbl_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_tim_hh_lbl_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_tim_hh_lbl_3, &ui_font_dseg7_20pt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_3_3 = lv_label_create(ui_settings_state);
    lv_obj_set_width(ui_label_3_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_3_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_3_3, 272);
    lv_obj_set_y(ui_label_3_3, 51);
    lv_label_set_text(ui_label_3_3, ":");
    ui_object_set_themeable_style_property(ui_label_3_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_label_3_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_label_3_3, &ui_font_dseg7_20pt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time_mm_lbl_3_1 = lv_label_create(ui_settings_state);
    lv_obj_set_width(ui_time_mm_lbl_3_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_mm_lbl_3_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time_mm_lbl_3_1, 276);
    lv_obj_set_y(ui_time_mm_lbl_3_1, 52);
    lv_label_set_text(ui_time_mm_lbl_3_1, "00");
    ui_object_set_themeable_style_property(ui_time_mm_lbl_3_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_time_mm_lbl_3_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_time_mm_lbl_3_1, &ui_font_dseg7_20pt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_3_4 = lv_label_create(ui_settings_state);
    lv_obj_set_width(ui_label_3_4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_3_4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_3_4, 12);
    lv_obj_set_y(ui_label_3_4, 96);
    lv_label_set_text(ui_label_3_4, "輝度");
    ui_object_set_themeable_style_property(ui_label_3_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_label_3_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_label_3_4, &ui_font_noto_sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blightness_sld_3 = lv_slider_create(ui_settings_state);
    lv_slider_set_value(ui_blightness_sld_3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_blightness_sld_3) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_blightness_sld_3, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_blightness_sld_3, 200);
    lv_obj_set_height(ui_blightness_sld_3, 10);
    lv_obj_set_x(ui_blightness_sld_3, 80);
    lv_obj_set_y(ui_blightness_sld_3, -10);
    lv_obj_set_align(ui_blightness_sld_3, LV_ALIGN_LEFT_MID);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_blightness_sld_3, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_blightness_sld_3,
                                                                                                       lv_obj_get_style_pad_right(ui_blightness_sld_3, LV_PART_MAIN) + 1, LV_PART_MAIN);

}

void ui_settings_state_screen_destroy(void)
{
    if(ui_settings_state) lv_obj_del(ui_settings_state);

    // NULL screen variables
    ui_settings_state = NULL;
    ui_header3 = NULL;
    ui_footer_3 = NULL;
    ui_back_btn_3 = NULL;
    ui_plus_btn_3 = NULL;
    ui_minus_btn_3 = NULL;
    ui_cursor_left_btn_3 = NULL;
    ui_cursor_right_btn_3 = NULL;
    ui_okay_btn_3 = NULL;
    ui_label_3_0 = NULL;
    ui_time_yyyy_lbl_3 = NULL;
    ui_label_3_1 = NULL;
    ui_time_mm_lbl_3_0 = NULL;
    ui_label_3_2 = NULL;
    ui_time_dd_lbl_3 = NULL;
    ui_tim_hh_lbl_3 = NULL;
    ui_label_3_3 = NULL;
    ui_time_mm_lbl_3_1 = NULL;
    ui_label_3_4 = NULL;
    ui_blightness_sld_3 = NULL;

}
