// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: m5-qrcode-pos

#include "ui/ui.h"

lv_obj_t * ui_sales_state = NULL;
lv_obj_t * ui_header_4 = NULL;
lv_obj_t * ui_footer_4 = NULL;
lv_obj_t * ui_back_btn_4 = NULL;
lv_obj_t * ui_sales_4 = NULL;
lv_obj_t * ui_label_4_0 = NULL;
lv_obj_t * ui_amount_price_lbl_4 = NULL;
lv_obj_t * ui_label_4_1 = NULL;
lv_obj_t * ui_label_4_2 = NULL;
lv_obj_t * ui_total_price_lbl_4 = NULL;
lv_obj_t * ui_label_4_3 = NULL;
lv_obj_t * ui_goods_list_4 = NULL;
lv_obj_t * ui_goods_list_title_lbl_4 = NULL;
lv_obj_t * ui_goods_list_number_lbl_4 = NULL;
lv_obj_t * ui_goods_list_price_lbl_4 = NULL;
// event funtions
void ui_event_back_btn_4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnSalesBackButtonClicked(e);
        _ui_screen_change(&ui_goods_state, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_goods_state_screen_init);
    }
}

// build funtions

void ui_sales_state_screen_init(void)
{
    ui_sales_state = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_sales_state, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_header_4 = ui_header_create(ui_sales_state);
    lv_obj_set_x(ui_header_4, 0);
    lv_obj_set_y(ui_header_4, 0);

    ui_footer_4 = lv_obj_create(ui_sales_state);
    lv_obj_set_width(ui_footer_4, 320);
    lv_obj_set_height(ui_footer_4, 48);
    lv_obj_set_x(ui_footer_4, 0);
    lv_obj_set_y(ui_footer_4, 192);
    lv_obj_remove_flag(ui_footer_4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_footer_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_footer_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue_darken_1);
    ui_object_set_themeable_style_property(ui_footer_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue_darken_1);
    lv_obj_set_style_border_width(ui_footer_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_footer_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_footer_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_footer_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_footer_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_back_btn_4 = lv_imagebutton_create(ui_footer_4);
    lv_imagebutton_set_src(ui_back_btn_4, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_arrow_back_48dp_e3e3e3_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_back_btn_4, 48);
    lv_obj_set_height(ui_back_btn_4, 48);
    lv_obj_set_align(ui_back_btn_4, LV_ALIGN_LEFT_MID);
    ui_object_set_themeable_style_property(ui_back_btn_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_back_btn_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_border_width(ui_back_btn_4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sales_4 = lv_obj_create(ui_sales_state);
    lv_obj_set_width(ui_sales_4, 320);
    lv_obj_set_height(ui_sales_4, 168);
    lv_obj_set_x(ui_sales_4, 0);
    lv_obj_set_y(ui_sales_4, 24);
    lv_obj_remove_flag(ui_sales_4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sales_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_sales_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(ui_sales_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(ui_sales_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_sales_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_sales_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_sales_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_sales_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_4_0 = lv_label_create(ui_sales_4);
    lv_obj_set_height(ui_label_4_0, 24);
    lv_obj_set_width(ui_label_4_0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_label_4_0, 24);
    lv_obj_set_y(ui_label_4_0, 120);
    lv_label_set_text(ui_label_4_0, "金額入力");
    ui_object_set_themeable_style_property(ui_label_4_0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_label_4_0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_label_4_0, &ui_font_noto_sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_amount_price_lbl_4 = lv_label_create(ui_sales_4);
    lv_obj_set_width(ui_amount_price_lbl_4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_amount_price_lbl_4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_amount_price_lbl_4, -48);
    lv_obj_set_y(ui_amount_price_lbl_4, 48);
    lv_obj_set_align(ui_amount_price_lbl_4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_amount_price_lbl_4, "0000000");
    ui_object_set_themeable_style_property(ui_amount_price_lbl_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_amount_price_lbl_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_amount_price_lbl_4, &ui_font_dseg7_20pt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_4_1 = lv_label_create(ui_sales_4);
    lv_obj_set_height(ui_label_4_1, 24);
    lv_obj_set_width(ui_label_4_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_label_4_1, 272);
    lv_obj_set_y(ui_label_4_1, 120);
    lv_label_set_text(ui_label_4_1, "円");
    ui_object_set_themeable_style_property(ui_label_4_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_label_4_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_label_4_1, &ui_font_noto_sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_4_2 = lv_label_create(ui_sales_4);
    lv_obj_set_height(ui_label_4_2, 24);
    lv_obj_set_width(ui_label_4_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_label_4_2, 24);
    lv_obj_set_y(ui_label_4_2, 144);
    lv_label_set_text(ui_label_4_2, "合計");
    ui_object_set_themeable_style_property(ui_label_4_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_label_4_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_label_4_2, &ui_font_noto_sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_total_price_lbl_4 = lv_label_create(ui_sales_4);
    lv_obj_set_width(ui_total_price_lbl_4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_total_price_lbl_4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_total_price_lbl_4, -48);
    lv_obj_set_y(ui_total_price_lbl_4, 72);
    lv_obj_set_align(ui_total_price_lbl_4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_total_price_lbl_4, "0000000");
    ui_object_set_themeable_style_property(ui_total_price_lbl_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_yellow_light_1);
    ui_object_set_themeable_style_property(ui_total_price_lbl_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_yellow_light_1);
    lv_obj_set_style_text_font(ui_total_price_lbl_4, &ui_font_dseg7_20pt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_4_3 = lv_label_create(ui_sales_4);
    lv_obj_set_height(ui_label_4_3, 24);
    lv_obj_set_width(ui_label_4_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_label_4_3, 272);
    lv_obj_set_y(ui_label_4_3, 144);
    lv_label_set_text(ui_label_4_3, "円");
    ui_object_set_themeable_style_property(ui_label_4_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_yellow_light_1);
    ui_object_set_themeable_style_property(ui_label_4_3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_yellow_light_1);
    lv_obj_set_style_text_font(ui_label_4_3, &ui_font_noto_sans, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goods_list_4 = lv_obj_create(ui_sales_4);
    lv_obj_set_width(ui_goods_list_4, 272);
    lv_obj_set_height(ui_goods_list_4, 120);
    lv_obj_set_x(ui_goods_list_4, 24);
    lv_obj_set_y(ui_goods_list_4, 0);
    lv_obj_set_style_radius(ui_goods_list_4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_goods_list_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(ui_goods_list_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    ui_object_set_themeable_style_property(ui_goods_list_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_goods_list_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_pad_left(ui_goods_list_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_goods_list_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_goods_list_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_goods_list_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goods_list_title_lbl_4 = lv_label_create(ui_goods_list_4);
    lv_obj_set_width(ui_goods_list_title_lbl_4, 160);
    lv_obj_set_height(ui_goods_list_title_lbl_4, LV_SIZE_CONTENT);    /// 1
    lv_label_set_long_mode(ui_goods_list_title_lbl_4, LV_LABEL_LONG_MODE_DOTS);
    lv_label_set_text(ui_goods_list_title_lbl_4, "商品タイトル");
    ui_object_set_themeable_style_property(ui_goods_list_title_lbl_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_goods_list_title_lbl_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_goods_list_title_lbl_4, &ui_font_noto_sans_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goods_list_number_lbl_4 = lv_label_create(ui_goods_list_4);
    lv_obj_set_width(ui_goods_list_number_lbl_4, 40);
    lv_obj_set_height(ui_goods_list_number_lbl_4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_goods_list_number_lbl_4, 160);
    lv_obj_set_y(ui_goods_list_number_lbl_4, 0);
    lv_label_set_text(ui_goods_list_number_lbl_4, "x000");
    ui_object_set_themeable_style_property(ui_goods_list_number_lbl_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_goods_list_number_lbl_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_goods_list_number_lbl_4, &ui_font_noto_sans_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goods_list_price_lbl_4 = lv_label_create(ui_goods_list_4);
    lv_obj_set_width(ui_goods_list_price_lbl_4, 72);
    lv_obj_set_height(ui_goods_list_price_lbl_4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_goods_list_price_lbl_4, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_goods_list_price_lbl_4, "000000円");
    ui_object_set_themeable_style_property(ui_goods_list_price_lbl_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_goods_list_price_lbl_4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_align(ui_goods_list_price_lbl_4, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_goods_list_price_lbl_4, &ui_font_noto_sans_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_back_btn_4, ui_event_back_btn_4, LV_EVENT_ALL, NULL);

}

void ui_sales_state_screen_destroy(void)
{
    if(ui_sales_state) lv_obj_del(ui_sales_state);

    // NULL screen variables
    ui_sales_state = NULL;
    ui_header_4 = NULL;
    ui_footer_4 = NULL;
    ui_back_btn_4 = NULL;
    ui_sales_4 = NULL;
    ui_label_4_0 = NULL;
    ui_amount_price_lbl_4 = NULL;
    ui_label_4_1 = NULL;
    ui_label_4_2 = NULL;
    ui_total_price_lbl_4 = NULL;
    ui_label_4_3 = NULL;
    ui_goods_list_4 = NULL;
    ui_goods_list_title_lbl_4 = NULL;
    ui_goods_list_number_lbl_4 = NULL;
    ui_goods_list_price_lbl_4 = NULL;

}
