// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: m5-qrcode-pos

#include "ui/ui.h"


const ui_theme_variable_t _ui_theme_color_blue_darken_1[1] = {0x42A5F5};
const ui_theme_variable_t _ui_theme_alpha_blue_darken_1[1] = {255};

const ui_theme_variable_t _ui_theme_color_white[1] = {0xE3E3E3};
const ui_theme_variable_t _ui_theme_alpha_white[1] = {255};

const ui_theme_variable_t _ui_theme_color_transparent[1] = {0x000000};
const ui_theme_variable_t _ui_theme_alpha_transparent[1] = {0};

const ui_theme_variable_t _ui_theme_color_yellow_light_1[1] = {0xFFEE58};
const ui_theme_variable_t _ui_theme_alpha_yellow_light_1[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

