// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: m5-qrcode-pos

#ifndef _M5_QRCODE_POS_UI_H
#define _M5_QRCODE_POS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "ui_goods_state.h"
#include "ui_amount_state.h"
#include "ui_payment_state.h"
#include "ui_settings_state.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(
    ui_img_battery_android_full_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/battery_android_full_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_barcode_scanner_48dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/barcode_scanner_48dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_add_48dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/add_48dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_remove_48dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/remove_48dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_currency_yen_48dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/currency_yen_48dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_shopping_cart_48dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/shopping_cart_48dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_settings_48dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/settings_48dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_arrow_back_ios_new_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/arrow_back_ios_new_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_arrow_forward_ios_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/arrow_forward_ios_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_arrow_back_48dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/arrow_back_48dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_money_off_48dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/money_off_48dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_check_48dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/check_48dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png

// FONTS
LV_FONT_DECLARE(ui_font_dseg7);
LV_FONT_DECLARE(ui_font_dseg7_20pt);
LV_FONT_DECLARE(ui_font_dseg7_32pt);
LV_FONT_DECLARE(ui_font_noto_sans);
LV_FONT_DECLARE(ui_font_noto_sans_16);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
