// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: m5-qrcode-pos

#ifndef UI_AMOUNT_STATE_H
#define UI_AMOUNT_STATE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_amount_state
extern void ui_amount_state_screen_init(void);
extern void ui_amount_state_screen_destroy(void);
extern lv_obj_t * ui_amount_state;
extern lv_obj_t * ui_header_1;
extern lv_obj_t * ui_footer_1;
extern void ui_event_payment_btn_1(lv_event_t * e);
extern lv_obj_t * ui_payment_btn_1;
extern void ui_event_back_btn_1(lv_event_t * e);
extern lv_obj_t * ui_back_btn_1;
extern lv_obj_t * ui_amount_1;
extern lv_obj_t * ui_label_1_0;
extern lv_obj_t * ui_label_1_1;
extern void ui_event_amount_price_spn_1(lv_event_t * e);
extern lv_obj_t * ui_amount_price_spn_1;
extern void ui_event_amount_plus_btn_1(lv_event_t * e);
extern lv_obj_t * ui_amount_plus_btn_1;
extern lv_obj_t * ui_label_1_2;
extern void ui_event_amount_minus_btn_1(lv_event_t * e);
extern lv_obj_t * ui_amount_minus_btn_1;
extern lv_obj_t * ui_label_1_3;
extern lv_obj_t * ui_goods_list_1;
extern lv_obj_t * ui_goods_list_title_lbl_1;
extern lv_obj_t * ui_goods_list_number_lbl_1;
extern lv_obj_t * ui_goods_list_price_lbl_1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

