// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: m5-qrcode-pos

#ifndef _UI_COMP_HEADER_H
#define _UI_COMP_HEADER_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT header
#define UI_COMP_HEADER_HEADER 0
#define UI_COMP_HEADER_BATTERY_IMG 1
#define UI_COMP_HEADER_TIME_LBL 2
#define _UI_COMP_HEADER_NUM 3
lv_obj_t * ui_header_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
