// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: m5-qrcode-pos

#ifndef UI_PAYMENT_STATE_H
#define UI_PAYMENT_STATE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_payment_state
extern void ui_payment_state_screen_init(void);
extern void ui_payment_state_screen_destroy(void);
extern lv_obj_t * ui_payment_state;
extern lv_obj_t * ui_header_2;
extern lv_obj_t * ui_footer_2;
extern void ui_event_back_btn_2(lv_event_t * e);
extern lv_obj_t * ui_back_btn_2;
extern void ui_event_free_btn_2(lv_event_t * e);
extern lv_obj_t * ui_free_btn_2;
extern void ui_event_okay_btn_2(lv_event_t * e);
extern lv_obj_t * ui_okay_btn_2;
extern lv_obj_t * ui_payment_2;
extern lv_obj_t * ui_goods_list_2;
extern lv_obj_t * ui_goods_list_title_lbl_2;
extern lv_obj_t * ui_goods_list_number_lbl_2;
extern lv_obj_t * ui_goods_list_price_lbl_2;
extern lv_obj_t * ui_label_2_0;
extern lv_obj_t * ui_sum_price_lbl_2;
extern lv_obj_t * ui_label_2_1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

