// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: m5-qrcode-pos

#ifndef UI_SETTINGS_STATE_H
#define UI_SETTINGS_STATE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settings_state
extern void ui_settings_state_screen_init(void);
extern void ui_settings_state_screen_destroy(void);
extern lv_obj_t * ui_settings_state;
extern lv_obj_t * ui_header3;
extern lv_obj_t * ui_footer_3;
extern lv_obj_t * ui_back_btn_3;
extern lv_obj_t * ui_plus_btn_3;
extern lv_obj_t * ui_minus_btn_3;
extern lv_obj_t * ui_cursor_left_btn_3;
extern lv_obj_t * ui_cursor_right_btn_3;
extern lv_obj_t * ui_okay_btn_3;
extern lv_obj_t * ui_label_3_0;
extern lv_obj_t * ui_time_yyyy_lbl_3;
extern lv_obj_t * ui_label_3_1;
extern lv_obj_t * ui_time_mm_lbl_3_0;
extern lv_obj_t * ui_label_3_2;
extern lv_obj_t * ui_time_dd_lbl_3;
extern lv_obj_t * ui_tim_hh_lbl_3;
extern lv_obj_t * ui_label_3_3;
extern lv_obj_t * ui_time_mm_lbl_3_1;
extern lv_obj_t * ui_label_3_4;
extern lv_obj_t * ui_blightness_sld_3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

