// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: m5-qrcode-pos

#ifndef UI_SALES_STATE_H
#define UI_SALES_STATE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_sales_state
extern void ui_sales_state_screen_init(void);
extern void ui_sales_state_screen_destroy(void);
extern lv_obj_t * ui_sales_state;
extern lv_obj_t * ui_header_4;
extern lv_obj_t * ui_footer_4;
extern void ui_event_back_btn_4(lv_event_t * e);
extern lv_obj_t * ui_back_btn_4;
extern lv_obj_t * ui_sales_4;
extern lv_obj_t * ui_label_4_0;
extern lv_obj_t * ui_amount_price_lbl_4;
extern lv_obj_t * ui_label_4_1;
extern lv_obj_t * ui_label_4_2;
extern lv_obj_t * ui_total_price_lbl_1;
extern lv_obj_t * ui_label_4_3;
extern lv_obj_t * ui_goods_list_4;
extern lv_obj_t * ui_goods_list_title_lbl_4;
extern lv_obj_t * ui_goods_list_number_lbl_4;
extern lv_obj_t * ui_goods_list_price_lbl_4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

