// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: m5-qrcode-pos

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BLUE_DARKEN_1 0
#define UI_THEME_COLOR_WHITE 1
#define UI_THEME_COLOR_TRANSPARENT 2
#define UI_THEME_COLOR_YELLOW_LIGHT_1 3

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_blue_darken_1[1];
extern const ui_theme_variable_t _ui_theme_alpha_blue_darken_1[1];

extern const ui_theme_variable_t _ui_theme_color_white[1];
extern const ui_theme_variable_t _ui_theme_alpha_white[1];

extern const ui_theme_variable_t _ui_theme_color_transparent[1];
extern const ui_theme_variable_t _ui_theme_alpha_transparent[1];

extern const ui_theme_variable_t _ui_theme_color_yellow_light_1[1];
extern const ui_theme_variable_t _ui_theme_alpha_yellow_light_1[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
